### ISSUE TITLE
An error occurred while imprinting the shape of the tool onto the mold

### ISSUE THREAD

**Issue by InfGithub** [ZLT9/create-modular-tools-fabric#4] opened 2024-11-21 15:58 UTC
The specific bug has been recorded as a video by me, but it takes up a lot of storage space and I can't upload it to Github. If there is another way I will try to send it to you. As you can see in the video, the texture does not update properly when the tool is embossed onto the mold, please fix it soon!
I was in a hurry, so I came up with this solution, which was to send a video of the bug report on the Chinese Bilibili website. Can you try browsing?
video:
【审核请快速通过！这个视频只是用来向其他人传输游戏错误的】 
https://www.bilibili.com/video/BV1ksUXY7E6B/

**Comment by ZLT9** [comment] 2024-11-21 17:22
Hi, thank you for sharing the video of the bug! I had a look, and it seems like you're using other mods alongside Create: Modular Tools. This could potentially be a compatibility issue with one of those mods. To help me investigate and fix the issue, could you please share a list of the mods you have installed? This will allow me to replicate your setup and pinpoint the cause of the problem.

**Comment by InfGithub** [comment] 2024-11-22 11:09
Minecraft Quilt 0.26.4 on Minecraft 1.20.1
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Beautify_美化
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Chinese_汉化
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Configs_配置
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Ctrls_控制
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\GamePlays_玩法
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Maps_地图
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Masa_高级辅助
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Optimize_优化
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Sodiums_渲染
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\architectury-9.2.14-fabric.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\cloth-config-11.1.136-fabric.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\collective-1.20.1-7.87.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\CreativeCore_FABRIC_v2.12.22_mc1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\fabric-language-kotlin-1.12.3+kotlin.2.0.21.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\Iceberg-1.20.1-fabric-1.1.25.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\libIPN-fabric-1.20-4.0.2.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\MagicLib-mc1.20.1-fabric-0.8.633-stable.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\malilib-fabric-1.20.1-0.16.3.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\mcpitanlib-2.5.2-1.20.1-fabric.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\Prism-1.20.1-fabric-1.0.5.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\APIs&LIBs_前置\quilt-api-7.6.0+0.92.2-1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\AdvancementPlaques-1.20.1-fabric-1.6.7.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\advancementscreenshot-1.20.1-4.9.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\appleskin-fabric-mc1.20.1-2.5.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\BetterAdvancements-Fabric-1.20.1-0.4.2.10.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\CustomSkinLoader_Fabric-14.21.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\inventoryhud.fabric.1.20.1-3.4.26.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\InventoryProfilesNext-fabric-1.20-1.10.11.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\Jade-1.20-Fabric-11.12.0.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\jei-1.20.1-fabric-15.20.0.105.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\Resourcify (1.20-1.20.1-fabric)-1.5.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\skinlayers3d-fabric-1.7.1-mc1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Auxs_辅助\WI-Zoom-1.5-MC1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Beautify_美化\chunksfadein-1.0.7-1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Beautify_美化\ItemBorders-1.20.1-fabric-1.2.2.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Beautify_美化\ItemPhysicLite_FABRIC_v1.6.5_mc1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Beautify_美化\LegendaryTooltips-1.20.1-fabric-1.4.5.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Beautify_美化\lootbeams-1.0.3.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Beautify_美化\quilt_loading_screen-6.1.0+1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Chinese_汉化\I18nUpdateMod-3.6.0-all.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Configs_配置\modmenu-7.2.2.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Ctrls_控制\jecharacters-1.20.1-fabric-4.5.4.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Ctrls_控制\ModernKeyBinding-Fabric-1.20-1.2.0.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\GamePlays_玩法\create-fabric-0.5.1-f-build.1417+mc1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\GamePlays_玩法\create_modular_tools-0.2.0+1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Maps_地图\open-parties-and-claims-fabric-1.20.1-0.23.2.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Maps_地图\XaerosWorldMap_1.39.0_Fabric_1.20.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Maps_地图\Xaeros_Minimap_24.6.1_Fabric_1.20.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Masa_高级辅助\litematica-fabric-1.20.1-0.15.4.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Masa_高级辅助\MasaGadget-mc1.20.1-fabric-4.0.373-stable.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Masa_高级辅助\minihud-fabric-1.20.1-0.27.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Masa_高级辅助\tweakeroo-fabric-1.20.1-0.17.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Optimize_优化\c2me-fabric-mc1.20.1-0.2.0+alpha.11.13.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Optimize_优化\ferritecore-6.0.1-fabric.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Optimize_优化\lithium-fabric-mc1.20.1-0.11.2.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Optimize_优化\starlight-1.1.2+fabric.dbc156f.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Sodiums_渲染\continuity-3.0.0-beta.5+1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Sodiums_渲染\indium-1.0.34+mc1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Sodiums_渲染\iris-1.7.5+mc1.20.1.jar
D:\Minecraft\.minecraft\versions\__Infinitive__'s modPack Quilt 0.26.4 on Minecraft 1.20.1\mods\Sodiums_渲染\sodium-fabric-0.5.11+mc1.20.1.jar

**Comment by ZLT9** [comment] 2024-11-22 23:18
I believe the bug is a compatibility issue with the Iris mod. I've attached a modified version of Create: Modular Tools 0.2.0 to this comment. Could you please test it by extracting the attached zip file and placing the included jar file into your mods folder? Let me know if this resolves the issue. If it does, I'll release an updated version with this fix on Modrinth soon. Thanks in advance for your help!

[create_modular_tools-0.2.0+1.20.1_iris_fix.zip](https://github.com/user-attachments/files/17877357/create_modular_tools-0.2.0%2B1.20.1_iris_fix.zip)

**Comment by InfGithub** [comment] 2024-11-27 12:44
That's it (the sword's stats are high because I turned on creative mode).

**Comment by InfGithub** [comment] 2024-11-27 12:44
![image](https://github.com/user-attachments/assets/2d463d5d-29bd-4b73-a786-da60972d0ba4)
![image](https://github.com/user-attachments/assets/94067ca4-0db4-474a-a529-19aa5ec5c0c5)
![image](https://github.com/user-attachments/assets/4b0e0f5e-e148-43a3-bae6-dd77c6a0380e)

**Comment by ZLT9** [comment] 2024-11-27 13:16
Great to hear! The fix will be included in a future update. Thank you again for reporting this bug!

**Closed as completed by ZLT9** 2024-11-27 13:16 UTC
